<?php include("header.phtml"); ?>
<!--[if lte IE 8]>
    <link rel="stylesheet" href="/styles/blog-old-ie.css">
<![endif]-->
<!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/styles/blog.css">
<!--<![endif]-->

    <div id="layout-about" class="">
        <div class="sidebar">
            <div class="header-about">
                <h1 class="brand-title">Project Team</h1>
                <h2 class="brand-tagline">Walter Mebane (Principal Investigator)</h2>
                <h2 class="brand-tagline">Allen Hicken (Principal Investigator)</h2>
                <h2 class="brand-tagline">David Backer (Researcher)</h2>
                <h2 class="brand-tagline">Ken Kollman (Researcher)</h2>
                <h2 class="brand-tagline">Lauren Guggenheim (Project Manager)</h2>
                <h2 class="brand-tagline">Kirill Kalinin (Research Associate)</h2>
                <h2 class="brand-tagline">Jonathan Wall (Research Assistant)</h2>
            </div>
        </div>
        <div class="content-about">
            <p><a href="https://www.isr.umich.edu/cps/" target="_blank"><img alt="logo" class="" src="images\CPSlogo.png"></a></p>
            <p><a href="https://www.usaid.gov/" target="_blank"><img alt="logo" class="" src="images\USAIDlogo.png"></a></p>
            <p><a href="http://www.electiondataarchive.org/" target="_blank"><img alt="logo" class="" src="images\CLEA.png"></a></p>
        </div>
    </div>

<?php include("footer.phtml"); ?>