<?php include("header.phtml"); ?>
<!--[if lte IE 8]>
    <link rel="stylesheet" href="/styles/blog-old-ie.css">
<![endif]-->
<!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/styles/blog.css">
<!--<![endif]-->

    <div id="layout-about" class="">
        <div class="sidebar">
            <div class="header-input">
                <?php include("inputform-maps.phtml"); ?>
            </div>
        </div>
        <div class="content-display">
            <?php 
                $images = $_SESSION["map_images"];
                foreach($images as $image) {
	                echo '<img src="'.$image.'" /><br />';
                }
            ?>
        </div>
    </div>

<?php include("footer.phtml"); ?>