<?php include("header.phtml"); ?>
<!--[if lte IE 8]>
    <link rel="stylesheet" href="/styles/blog-old-ie.css">
<![endif]-->
<!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/styles/blog.css">
<!--<![endif]-->
<style>
   
</style>
    <div id="layout-about" class="">
        <div class="sidebar">
            <div class="header-input">
                <?php include("inputform.phtml"); ?>
            </div>
        </div>
        <div class="content-display">
            <p style="white-space: pre; font-family: 'Courier New'; margin: 0; padding: 0; border: solid 1px; ">
            <?php
                $summary_filename = __DIR__ . "/../public/Results/summary_" . session_id() . ".txt";
                if(file_exists($summary_filename)){
                    $text = file_get_contents($summary_filename);
                    $trimmed = ltrim($text);
                    echo $trimmed;
                }
            ?> 
            </p>   
        </div>
    </div>

<?php include("footer.phtml"); ?>